### ISSUE TITLE
Refactor User Guide to be more user-centric

### ISSUE THREAD

**Issue by Asthenosphere** [AY2021S1-CS2103T-T11-1/tp#64]
- Rewrite introduction 
- Quick Start: must have a preface. Cannot just start with numbers. 
- Features: Must talk to the person rather than giving just an instruction. "This feature adds a person to the Address Book..."
- Examples must be accompanied with an outcome. Must state what to do with the example / where to type. "Suppose you want to add a new contact John Doe to the address book ... You will see John Doe added to... you will also see a message in the result display box...". Provide step by step for just one example (within a feature). Other examples can just be listed.

**Comment by sebastiantoh** [comment]
### UI Terminology:
- **Result Box**
- **Command Box**
- **Contact List**
- **Sale List**
- **Sales Tag**
- **Contact Tags**
- **Meeting List**
- **Reminder List**

Any reference to the above should be in **bold** and capitalized accordingly. Feel free to call them something else, just need to make sure it's consistent throughout

###  Cover Page
- Must have the word "User Guide"

### Table of Contents
- Should be before the introduction
- Must be numbered (OK to have bullets)
- Ensure proper casing (for simplicity, **I suggest that we all stick to sentence case - capitalise ONLY first word, with the exception of proper nouns**)
- Check that links are working
- Parallel structure for each feature
  - **I suggest the following format:** 
    - ___ing ____: `command word`
    - E.g. Adding a contact: `contact add`
    - Note that extra parameters to the command are omitted

### Introduction (DONE)
- Overview of Product - first statement tells you what the app is, next statement tells you target audience, followed by main features + how it is designed using CLI with GUI (explain these technical jargon  - CLI and GUI. Should also be written out in full the first time you mention in instead of abbreviating them)
  - See: OASIS example
- Purpose of Document
- Section explaining how to read the guide
    - Explain any special notations, markups, symbols, navigation

### Individual Features

- Note: Anything not marked with a name will be considered a team effort. So do indicate your names to the respective sections that you've written.
- Ordering of features within each section: **let's standardise it to: List, Add, Delete, Edit, followed by other miscellaneous commands that are related to that particular model**. 
- **Steps must be numbered and start with a verb**. For results, should be “The result box will …”
- For each step, explain what needs to be done first, then display an image. Ensure that the image matches what you say needs to be typed. **Image after the step**.
- To explain features which require some form of INDEX, first tell the user to type the list command and explain why this is necessary. Then, "Let's assume that ... has index ..."

**Let's standardise the format for writing each feature:**

``` markdown
### Reminders 

<include preface statement>

#### Adding reminders: `reminder add` \[Sebastian Toh Shi Jian\]

<include preface statement that follows the below form - "Adds ..." >
Adds a reminder scheduled on a particular date that is associated with the specified contact to StonksBook.

<any notes if applicable - should be wrapped in a div tag with the appropriate classes so that it gets rendered as a note>

**Format**: `reminder add c/CONTACT_INDEX m/MESSAGE d/DATETIME`

* Adds a reminder associated with the contact at the specified `CONTACT_INDEX`.
* The index refers to the index number shown in the displayed contact list.
* The index must be a positive integer 1, 2, 3, …​
* The datetime must be in the format `yyyy-MM-dd HH:mm`

**Example**: 
Suppose you want to .... This is what you need to do:

<EACH STEP SHOULD END WITH A FULL STOP>
1. Type ____ in the **Command Box** and press <kbd>Enter</kbd>.

<IMAGE FOR STEP 1 - WIDTH SHOULD BE 900>

<figure>
  <img src="images/meetingListMockup.png" alt="result for 'meeting list'" width="900px">
  <figcaption>Fig. **{TODO}** - Meeting List Mockup.</figcaption>
</figure>

2. ....

<image for step 2>

3. ...

4. The **Result Box** will ... and the **Reminder List** will ...

```


### Command Summary (DONE)
- **Let's split our command summary based on how we split the `Features` section in our UG**. So we'll have multiple command summary tables. Remember to add a preface between the headers for each section!
- Within each section, the **command summary table should be sorted in ascending order alphabetically.**
- SEE: FitBiz's Command Summary
- **I also propose splitting the examples into a third column of it's own:**

Here's the template:
```markdown
| Command                                                                   | Summary                      | Example (if applicable)                                                                                                          |
|---------------------------------------------------------------------------|------------------------------|----------------------------------------------------------------------------------------------------------------------------------|
| `contact add n/NAME p/PHONE_NUMBER e/EMAIL a/ADDRESS [t/TAG]…[r/REMARK]…` | Adds a contact to StonksBook | `contact add n/James Ho p/22224444 e/jamesho@example.com a/123, Clementi Rd, 1234665 t/friend t/colleague r/birthday: 20 August` |
|                                                                           |                              |                                                                                                                                  |
|                                                                           |                              |                                                                                                                                  |
```

### Stuff in General
- Avoid excessive paragraphing (should not have multiple paragraphs with only 1 sentence each)
- Should refer to the reader directly.
  - e.g. "You should ..." rather than "Users should ..."
- **MUST always have a preface between headers**
  - e.g. in Quick Start, before listing down the steps, add something like: "To get started, following these simple steps:”
- Informal diagrams, which follows right after the text, need not be labelled.
- Insert page numbers
- Be as concise as possible. 

### Other Stuff to Standardise
- **Let's use `<kbd></kbd>` to denote keystrokes. e.g. `<kbd>Enter</kbd>` to get <kbd>Enter</kbd>** 
- Labelling of figures: **I think we should KIV this first**, until we're all done with the UG, otherwise if we were to all add labels, we might have to constantly update the label numbers. 
- Sections should be numbered - let's not worry about this for now too. **I think there are tools available to automatically number it for us. I don't think it's necessary for us to manually write the numbering in your headers**
- Let's use red for any image annotations, and rounded rectangles over sharp-cornered rectangles
- Any screenshots of the UI should omit the top menu (so that the images look consistent regardless of OS)

**Comment by sebastiantoh** [comment]
Resolved
